spring:
  application:
    name: lottery
  datasource:
    url: jdbc:postgresql://localhost:5432/lottery?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true




