
spring:
  application:
    name: lottery
  datasource:
    url: jdbc:postgresql://localhost:5432/lottery?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: 192.168.0.20:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: history
      auto-offset-reset: earliest
server:
  port: 8080



